### ISSUE TITLE
undefined symbol: gsl_sf_bessel_J0

### ISSUE THREAD

**Issue by eserte** [PerlAlien/Alien-GSL#12]
t/alien_gsl.t fails on some of my smokers:
```
# Failed test 'xs'
# at t/alien_gsl.t line 11.
#   XSLoader failed
#     Can't load '/home/cpansand/.cpan/build/2021060316/Alien-GSL-1.03-0/_alien/tmp/test-alien-W1J5a3/auto/Test/Alien/XS/Mod0AAAA/Mod0AAAA.so' for module Test::Alien::XS::Mod0AAAA: /home/cpansand/.cpan/build/2021060316/Alien-GSL-1.03-0/_alien/tmp/test-alien-W1J5a3/auto/Test/Alien/XS/Mod0AAAA/Mod0AAAA.so: undefined symbol: gsl_sf_bessel_J0 at /opt/perl-5.28.1/lib/5.28.1/x86_64-linux/DynaLoader.pm line 193.
# # Compilation failed in require at /home/cpansand/.cpan/build/2021060316/Alien-Build-2.40-0/blib/lib/Test/Alien.pm line 422.
# BEGIN failed--compilation aborted at /home/cpansand/.cpan/build/2021060316/Alien-Build-2.40-0/blib/lib/Test/Alien.pm line 422.
t/alien_gsl.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```

Looking at http://matrix.cpantesters.org/?dist=Alien-GSL%201.03;os=linux;reports=1#sl=2,0 this seems to happen on Fedora & CentOS 7 systems, but there are also configurations on these OS with passing tests.

**Comment by plicease** [comment]
I probably picked a symbol to test against that isn't available in those versions of GSL.

@hakonhagland @leto could you provide either a required version number of GSL or a C test that I run at configure and test time to ensure that the system GSL is sufficient and if not, do a share install.

/cc: @jberger

**Comment by hakonhagland** [comment]
I also see that version 2.7 of GSL was [released 9 days ago](https://www.gnu.org/software/gsl/#releases). Maybe it is trying to download the new version, and we do not yet have support for it in [Math::GSL](https://github.com/leto/math--gsl) ?

**Comment by hakonhagland** [comment]
> this seems to happen on Fedora & CentOS 7 systems

It also happens on macOS. I tested this on macOS Big Sur 11.2.3 

```
$ perl Makefile.PL
$ make
$ make test
"/Users/hakonhaegland/perl5/perlbrew/perls/perl-5.32.0/bin/perl" -MAlien::Build::MM=cmd -e test
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
PERL_DL_NONLAZY=1 "/Users/hakonhaegland/perl5/perlbrew/perls/perl-5.32.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/alien_gsl.t .. 2/?
# Failed test 'xs'
# at t/alien_gsl.t line 11.
#   ExtUtils::CBuilder->compile failed
#     error building /Users/hakonhaegland/perl/github/Alien-GSL/_alien/tmp/test-alien-B30WGv/test.o from '/Users/hakonhaegland/perl/github/Alien-GSL/_alien/tmp/test-alien-B30WGv/test.c' at /Users/hakonhaegland/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/ExtUtils/CBuilder/Base.pm line 185.
#     cc -I/Users/hakonhaegland/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/darwin-2level/CORE -I/Users/hakonhaegland/perl/github/Alien-GSL/blib/lib/auto/share/dist/Alien-GSL/include -c -fno-common -DPERL_DARWIN -mmacosx-version-min=11.1 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3 -o /Users/hakonhaegland/perl/github/Alien-GSL/_alien/tmp/test-alien-B30WGv/test.o /Users/hakonhaegland/perl/github/Alien-GSL/_alien/tmp/test-alien-B30WGv/test.c
#     /Users/hakonhaegland/perl/github/Alien-GSL/_alien/tmp/test-alien-B30WGv/test.xs:9:14: error: implicit declaration of function 'gsl_sf_bessel_J0' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
#       double y = gsl_sf_bessel_J0 (x);
#                  ^
#     1 error generated.
t/alien_gsl.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests

Test Summary Report
-------------------
t/alien_gsl.t (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=1, Tests=3,  1 wallclock secs ( 0.03 usr  0.02 sys +  0.63 cusr  0.29 csys =  0.97 CPU)
Result: FAIL
Failed 1/1 test programs. 1/3 subtests failed.
make: *** [test_dynamic] Error 1

```

**Comment by plicease** [comment]
It's possible that the missing header is causing the Fedora+CentOS issue, but these are different errors.  Fedora+CentOS is a linker error, and the macOS error is a compiler error (incorrect IMO).  @eserte can you confirm if 1.04 (which includes #13) fixes the problem you observed on your smokers?

**Comment by hakonhagland** [comment]
> Fedora+CentOS is a linker error, and the macOS error is a compiler error

Good observation. I missed that but I see now that the output from `make test` is different.

> this seems to happen on Fedora & CentOS 7 systems, but there are also configurations on these OS with passing tests.

I tried now to install 1.04 in a docker container with CentOS 7 and it installed fine there (no failing tests).

**Comment by plicease** [comment]
I am still getting the same cpantester fails with the link error, which means, although it is possible to build on Fedora/CentOS whatever way we are doing that isn't reproducing the problem.

I've added Fedora to CI in a PR #14 and it passes for system install but fails in a totally different way for share install
https://github.com/PerlAlien/Alien-GSL/pull/14/checks?check_run_id=3163374500

**Comment by plicease** [comment]
The dev version (1.05_01) 
https://metacpan.org/release/PLICEASE/Alien-GSL-1.05_01
contains additional diagnostics which may be helpful for diagnosing this.  Some of the diagnostics can unfortunately only be seen by running:

 `prove -bvm t/alien_gsl.t`

@eserte I can peek at the ct matrix for the diagnostics visible there, but if you can provide the output of the verbose prove that would be great.

**Comment by eserte** [comment]
On a centos7 system with perl 5.30.1:
```
$ perl5.30.1 -S prove -bvm t/alien_gsl.t
t/alien_gsl.t .. 
ok 1 - Alien::GSL responds to: cflags libs dynamic_libs bin_dir
# detect module name Test::Alien::XS::Mod0
# parse xs /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.xs => /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.c
# 
# compile /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.c
# cc -I/opt/perl-5.30.1/lib/5.30.1/x86_64-linux/CORE -fPIC -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -o /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.o /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.c
# ---
# compile_options:
#   extra_compiler_flags: []
#   source: /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.c
# link /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.o
# cc -shared -O2 -L/usr/local/lib -fstack-protector-strong -shared -O2 -L/usr/local/lib -fstack-protector-strong -o /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.so /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.o
# ---
# link_options:
#   extra_linker_flags: []
#   module_name: Test::Alien::XS::Mod0
#   objects:
#     - /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.o
# created lib /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/test.so
ok 2 - xs
/opt/perl-5.30.1/bin/perl: symbol lookup error: /home/cpansand/.cpan/build/2021072807/Alien-GSL-1.05_01-0/_alien/tmp/test-alien-cqydF2/auto/Test/Alien/XS/Mod0/Mod0.so: undefined symbol: gsl_sf_bessel_J0
Dubious, test returned 127 (wstat 32512, 0x7f00)
All 2 subtests passed 

Test Summary Report
-------------------
t/alien_gsl.t (Wstat: 32512 Tests: 2 Failed: 0)
  Non-zero exit status: 127
  Parse errors: No plan found in TAP output
Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.38 cusr  0.11 csys =  0.52 CPU)
Result: FAIL
```

**Comment by plicease** [comment]
@eserte interesting it looks like it is attempting a system install but for some reason hasn't gotten any compiler/linker flags from pkg-config.  I was not able to reproduce with my centos 7 container environment.  (Tried both real pkg-config and the pure-perl PkgConfig.pm and both worked for me).

Can you provide the output of:

 * `pkg-config --modversion gsl`  (if `pkg-config` is not installed then AB will use `ppkg-config`)
 * `pkg-config --libs gsl`
 * `perl Makefile.PL && make` (from a freshly extracted Alien-GSL).

**Comment by eserte** [comment]
It seems that the problem is that an older Alien::Build version was installed. The problem can be reproduced with the following Dockerfile:
```
# docker build -t perl-test . && docker run perl-test
# https://github.com/PerlAlien/Alien-GSL/issues/12
FROM centos:7
RUN yum install -y perl-CPAN gcc perl-Test perl-Test-Simple perl-App-cpanminus gsl-devel
RUN yum install -y perl-LWP-Protocol-https
RUN cpanm https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Build-1.94.tar.gz
CMD cpan -t Alien::GSL
```

**Comment by plicease** [comment]
Ahhh!   I suspect that the configure time AB being different from the runtime requirement is the problem.  I think this might sort it:

**Comment by plicease** [comment]
@eserte can you confirm if https://metacpan.org/release/PLICEASE/Alien-GSL-1.06_01 helps?  If that solves it then we can close this.

**Comment by eserte** [comment]
Yes, looks good.

**Comment by plicease** [comment]
> Yes, looks good.

Great thanks you for the original report plus the subsequent reports.  I'm uploading a production version as 1.07.
